[package]
edition = "2021"
name = "elysium-sdl"
version = "0.0.0"

[dependencies.elysium-mem]
path = "../../mem"

[dependencies.frosting]
git = "https://github.com/elysian6969/frosting"

[dependencies.link]
git = "https://github.com/elysian6969/link"
