use {
    bevy::{input::keyboard::KeyCode, prelude::*},
    sdl2::{keyboard, mouse},
};

pub fn mouse_button(button: mouse::MouseButton) -> MouseButton {
    use mouse::MouseButton::*;

    match button {
        Left => MouseButton::Left,
        Middle => MouseButton::Middle,
        Right => MouseButton::Right,
        X1 => MouseButton::Other(4),
        X2 => MouseButton::Other(5),
        _ => MouseButton::Other(6),
    }
}

pub fn key_code(key_code: keyboard::Keycode) -> Option<KeyCode> {
    use keyboard::Keycode::*;

    let key_code = match key_code {
        Kp0 => KeyCode::Key0,
        Kp1 => KeyCode::Key1,
        Kp2 => KeyCode::Key2,
        Kp3 => KeyCode::Key3,
        Kp4 => KeyCode::Key4,
        Kp5 => KeyCode::Key5,
        Kp6 => KeyCode::Key6,
        Kp7 => KeyCode::Key7,
        Kp8 => KeyCode::Key8,
        Kp9 => KeyCode::Key9,

        A => KeyCode::A,
        B => KeyCode::B,
        C => KeyCode::C,
        D => KeyCode::D,
        E => KeyCode::E,
        F => KeyCode::F,
        G => KeyCode::G,
        H => KeyCode::H,
        I => KeyCode::I,
        J => KeyCode::J,
        K => KeyCode::K,
        L => KeyCode::L,
        M => KeyCode::M,
        N => KeyCode::N,
        O => KeyCode::O,
        P => KeyCode::P,
        Q => KeyCode::Q,
        R => KeyCode::R,
        S => KeyCode::S,
        T => KeyCode::T,
        U => KeyCode::U,
        V => KeyCode::V,
        W => KeyCode::W,
        X => KeyCode::X,
        Y => KeyCode::Y,
        Z => KeyCode::Z,

        Escape => KeyCode::Escape,

        F1 => KeyCode::F1,
        F2 => KeyCode::F2,
        F3 => KeyCode::F3,
        F4 => KeyCode::F4,
        F5 => KeyCode::F5,
        F6 => KeyCode::F6,
        F7 => KeyCode::F7,
        F8 => KeyCode::F8,
        F9 => KeyCode::F9,
        F10 => KeyCode::F10,
        F11 => KeyCode::F11,
        F12 => KeyCode::F12,
        F13 => KeyCode::F13,
        F14 => KeyCode::F14,
        F15 => KeyCode::F15,
        F16 => KeyCode::F16,
        F17 => KeyCode::F17,
        F18 => KeyCode::F18,
        F19 => KeyCode::F19,
        F20 => KeyCode::F20,
        F21 => KeyCode::F21,
        F22 => KeyCode::F22,
        F23 => KeyCode::F23,

        PrintScreen => KeyCode::Snapshot,
        ScrollLock => KeyCode::Scroll,
        Pause => KeyCode::Pause,
        Insert => KeyCode::Insert,
        Home => KeyCode::Home,
        Delete => KeyCode::Delete,
        End => KeyCode::End,
        PageDown => KeyCode::PageDown,
        PageUp => KeyCode::PageUp,
        Left => KeyCode::Left,
        Up => KeyCode::Up,
        Right => KeyCode::Right,
        Down => KeyCode::Down,
        Back => KeyCode::Back,
        Return => KeyCode::Return,
        Space => KeyCode::Space,
        Caret => KeyCode::Caret,

        NumLockClear => KeyCode::Numlock,
        Num0 => KeyCode::Numpad0,
        Num1 => KeyCode::Numpad1,
        Num2 => KeyCode::Numpad2,
        Num3 => KeyCode::Numpad3,
        Num4 => KeyCode::Numpad4,
        Num5 => KeyCode::Numpad5,
        Num6 => KeyCode::Numpad6,
        Num7 => KeyCode::Numpad7,
        Num8 => KeyCode::Numpad8,
        Num9 => KeyCode::Numpad9,

        Quote => KeyCode::Apostrophe,
        Asterisk => KeyCode::Asterisk,
        KpPlus => KeyCode::Plus,
        At => KeyCode::At,
        Backslash => KeyCode::Backslash,
        Calculator => KeyCode::Calculator,
        CapsLock => KeyCode::Capital,
        Colon => KeyCode::Colon,
        Comma => KeyCode::Comma,
        Equals => KeyCode::Equals,
        LAlt => KeyCode::LAlt,
        LeftBracket => KeyCode::LBracket,
        LCtrl => KeyCode::LControl,
        LShift => KeyCode::LShift,
        LGui => KeyCode::LWin,
        Mail => KeyCode::Mail,
        MediaSelect => KeyCode::MediaSelect,
        Minus => KeyCode::Minus,
        Mute => KeyCode::Mute,
        Computer => KeyCode::MyComputer,
        Period => KeyCode::Period,
        AudioPlay => KeyCode::PlayPause,
        Power => KeyCode::Power,
        AudioPrev => KeyCode::PrevTrack,
        RAlt => KeyCode::RAlt,
        RightBracket => KeyCode::RBracket,
        RCtrl => KeyCode::RControl,
        RShift => KeyCode::RShift,
        RGui => KeyCode::RWin,
        Semicolon => KeyCode::Semicolon,
        Slash => KeyCode::Slash,
        Sleep => KeyCode::Sleep,
        Stop => KeyCode::Stop,
        Sysreq => KeyCode::Sysrq,
        Tab => KeyCode::Tab,
        Underscore => KeyCode::Underline,
        VolumeDown => KeyCode::VolumeDown,
        VolumeUp => KeyCode::VolumeUp,

        AcBookmarks => KeyCode::WebFavorites,
        AcForward => KeyCode::WebForward,
        AcHome => KeyCode::WebHome,
        AcRefresh => KeyCode::WebRefresh,
        AcSearch => KeyCode::WebSearch,
        AcStop => KeyCode::WebStop,

        _ => return None,
    };

    Some(key_code)
}
