[package]
edition = "2021"
name = "elysium"
version = "0.0.0"

[dependencies]
cake = { branch = "old", default-features = false, git = "https://github.com/elysian6969/cake" }
elysium-input = { default-features = false, path = "crates/input" }
elysium-math = { default-features = false, path = "crates/math" }
elysium-mem = { default-features = false, path = "crates/mem" }
elysium-pattern = { default-features = false, path = "crates/pattern" }
elysium-sdk = { default-features = false, path = "crates/sdk" }
iced_glow = { default-features = false, git = "https://github.com/elysian6969/iced" }
iced_native = { default-features = false, features = ["debug"], git = "https://github.com/elysian6969/iced" }
libc = { default-features = false, version = "0.2" }
libm = { default-features = false, git = "https://github.com/elysian6969/libm" }
#link = { default-features = false, git = "https://github.com/elysian6969/link" }
link = { default-features = false, path = "../link" }
num-traits = { default-features = false, version = "0.2" }
palette = { default-features = false, version = "0.6" }
rand = { default-features = false, version = "0.8" }
sdl2-sys = { default-features = false, version = "0.35" }

[workspace]
members = [
    "crates/input",
    "crates/math",
    "crates/mem",
    "crates/pattern",
    "crates/sdk",
]
