[package]
edition = "2021"
name = "elysium"
version = "0.0.0"

[dependencies]
bevy = { version = "0.10.1", default-features = false }
bevy_source = { version = "0.0.0", path = "crates/bevy", default-features = false }
leafwing-input-manager = { version = "0.9.2", default-features = false }
libm = { version = "0.2.6", default-features = false }

[[bin]]
name = "csgo_linux64"
path = "src/main.rs"

[profile.dev]
opt-level = 2

[profile.release]
lto = "fat"
strip = "symbols"

[workspace]
members = ["crates/bevy", "crates/bevy_internal", "crates/sys"]
