[package]
name = "snowdrop"
version = "0.1.0"
edition = "2024"

[dependencies]
libloading = "0.8.8"
tracing = { version = "0.1.41", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.3.19", default-features = false, features = ["ansi", "env-filter"] }
