[package]
edition = "2021"
name = "elysium"
version = "0.0.0"

[dependencies.clap]
default-features = false
features = ["color", "derive", "help", "std", "suggestions", "usage"]
version = "4.1"

[dependencies.bevy]
default-features = false
version = "0.9"

[dependencies.bevy_log]
version = "0.9"

[dependencies.dirs]
version = "4.0"

[dependencies.elysium-sdk]
path = "crates/sdk"

[dependencies.thiserror]
version = "1.0"

[dependencies.tracing]
default-features = false
features = ["std"]
version = "0.1"

[dependencies.vdf]
default-features = false
git = "https://github.com/elysian6969/esteem"
rev = "3783f7e560e1a601f7e24859ab49526aaf9da113"

[profile.dev]
opt-level = 2

[profile.release]
strip = "symbols"

[workspace]
members = [
    "crates/dismal",
    "crates/mem",
    "crates/sdk",
]
