[package]
edition = "2021"
name = "elysium"
version = "0.0.0"

[dependencies]
cake = { git = "https://github.com/elysian6969/cake" }
daisy_chain = { path = "crates/daisy_chain" }
elysium-input = { path = "crates/input" }
elysium-math = { path = "crates/math" }
elysium-mem = { path = "crates/mem" }
elysium-sdk = { path = "crates/sdk" }
iced_glow = { git = "https://github.com/iced-rs/iced" }
iced_native = { features = ["debug"], git = "https://github.com/iced-rs/iced" }
libm = { git = "https://github.com/elysian6969/libm" }
link = { git = "https://github.com/elysian6969/link" }
# rename when
providence-model = { path = "crates/model" }
providence-pattern = { path = "crates/pattern" }
sdl2-sys = "0.35"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
lto = "fat"

[workspace]
members = [
    "crates/input",
    "crates/mem",
    "crates/sdk",
]
