[package]
edition = "2021"
name = "elysium"
version = "0.0.0"

[dependencies]
bevy = { version = "0.10.0", default-features = false }
clap = { version = "4.1.11", default-features = false, features = ["color", "derive", "env", "help", "std", "suggestions", "unicode", "usage", "wrap_help"] }
dirs = { version = "4.0.0", default-features = false }
elysium-sdk = { default-features = false, path = "crates/sdk" }
vdf = { default-features = false, git = "https://github.com/elysian6969/esteem", rev = "3783f7e560e1a601f7e24859ab49526aaf9da113" }

[profile.dev]
opt-level = 2

[profile.release]
strip = "symbols"

[workspace]
members = ["crates/dismal", "crates/sdk"]
