[package]
edition = "2021"
name = "elysium"
version = "0.0.0"

[dependencies]
daisy_chain = { path = "crates/daisy_chain" }
elysium-input = { path = "crates/input" }
elysium-math = { path = "crates/math" }
elysium-mem = { path = "crates/mem" }
elysium-menu = { path = "crates/menu" }
elysium-sdk = { path = "crates/sdk" }
iced_glow = { git = "https://github.com/iced-rs/iced" }
iced_native = { git = "https://github.com/iced-rs/iced" }

[dependencies.frosting]
default-features = false
git = "https://github.com/elysian6969/frosting"

[dependencies.libm]
default-features = false
git = "https://github.com/elysian6969/libm"

[dependencies.link]
default-features = false
#git = "https://github.com/elysian6969/link"
path = "../link"

[dependencies.providence-model]
default-features = false
path = "crates/model"

[dependencies.providence-pattern]
default-features = false
path = "crates/pattern"

[dependencies.sdl2-sys]
default-features = false
version = "0.35"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
lto = "fat"

[workspace]
members = [
    "crates/input",
    "crates/mem",
    "crates/menu",
    "crates/sdk",
]
