[package]
edition = "2021"
name = "elysium-sdk"
version = "0.0.0"

[dependencies.bevy]
default-features = false
version = "0.9"

[dependencies.bitflags]
version = "1.3"

[dependencies.dirs]
version = "4.0"

[dependencies.elysium-input]
path = "../input"

[dependencies.elysium-mem]
path = "../mem"

[dependencies.iced_aw]
default-features = false
features = ["color_picker", "glow", "tabs"]
git = "https://github.com/iced-rs/iced_aw"
rev = "c6a3bfdc4d01d28aeb433d42628e80a620f78bb3"

[dependencies.iced_glow]
version = "0.4"

[dependencies.iced_lazy]
version = "0.2"

[dependencies.iced_native]
version = "0.6"

[dependencies.libc]
version = "0.2"

[dependencies.link]
default-features = false
git = "https://github.com/elysian6969/link"
rev = "0c54d56d5472a996a59f6e2bf18e603340ddf48f"

[dependencies.libloading]
version = "0.7"

[dependencies.once_cell]
version = "1.16"

[dependencies.regex]
version = "1.6"

[dependencies.phf]
features = ["macros"]
version = "0.11"

[dependencies.rand]
version = "0.8"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.serde_json]
version = "1.0"

[dependencies.sdl2-sys]
version = "0.35"
[dependencies.thiserror]
version = "1.0"

[dependencies.tracing]
default-features = false
features = ["std"]
version = "0.1"

[dependencies.ubyte]
version = "0.10"
