[package]
edition = "2021"
name = "elysium-sdk"
version = "0.0.0"

[dependencies.bevy]
default-features = false
features = ["render"]
version = "0.9"

[dependencies.bitflags]
version = "1.3"

[dependencies.elysium-mem]
path = "../mem"

[dependencies.libc]
version = "0.2"

[dependencies.link]
default-features = false
git = "https://github.com/elysian6969/link"
rev = "0c54d56d5472a996a59f6e2bf18e603340ddf48f"

[dependencies.libloading]
version = "0.7"

[dependencies.once_cell]
version = "1.16"

[dependencies.regex]
version = "1.6"

[dependencies.phf]
features = ["macros"]
version = "0.11"

[dependencies.thiserror]
version = "1.0"

[dependencies.tracing]
default-features = false
features = ["std"]
version = "0.1"

[dependencies.ubyte]
version = "0.10"
