[package]
edition = "2021"
name = "elysium-sdk"
version = "0.0.0"

[dependencies.bevy]
default-features = false
version = "0.9"

[dependencies.bitflags]
version = "1.3"

[dependencies.elysium-mem]
path = "../mem"

[dependencies.libc]
version = "0.2"

[dependencies.phf]
features = ["macros"]
version = "0.11"

[dependencies.tracing]
default-features = false
features = ["std"]
version = "0.1"
