use {
    bevy::{input::keyboard::KeyCode, prelude::*},
    sdl2::{keyboard, mouse},
};

pub fn mouse_button(button: mouse::MouseButton) -> MouseButton {
    match button {
        mouse::MouseButton::Left => MouseButton::Left,
        mouse::MouseButton::Middle => MouseButton::Middle,
        mouse::MouseButton::Right => MouseButton::Right,
        mouse::MouseButton::X1 => MouseButton::Other(4),
        mouse::MouseButton::X2 => MouseButton::Other(5),
        _ => MouseButton::Other(6),
    }
}

pub fn key_code(key_code: keyboard::Keycode) -> Option<KeyCode> {
    use keyboard::Keycode;

    let key_code = match key_code {
        Keycode::Kp0 => KeyCode::Key0,
        Keycode::Kp1 => KeyCode::Key1,
        Keycode::Kp2 => KeyCode::Key2,
        Keycode::Kp3 => KeyCode::Key3,
        Keycode::Kp4 => KeyCode::Key4,
        Keycode::Kp5 => KeyCode::Key5,
        Keycode::Kp6 => KeyCode::Key6,
        Keycode::Kp7 => KeyCode::Key7,
        Keycode::Kp8 => KeyCode::Key8,
        Keycode::Kp9 => KeyCode::Key9,

        Keycode::A => KeyCode::A,
        Keycode::B => KeyCode::B,
        Keycode::C => KeyCode::C,
        Keycode::D => KeyCode::D,
        Keycode::E => KeyCode::E,
        Keycode::F => KeyCode::F,
        Keycode::G => KeyCode::G,
        Keycode::H => KeyCode::H,
        Keycode::I => KeyCode::I,
        Keycode::J => KeyCode::J,
        Keycode::K => KeyCode::K,
        Keycode::L => KeyCode::L,
        Keycode::M => KeyCode::M,
        Keycode::N => KeyCode::N,
        Keycode::O => KeyCode::O,
        Keycode::P => KeyCode::P,
        Keycode::Q => KeyCode::Q,
        Keycode::R => KeyCode::R,
        Keycode::S => KeyCode::S,
        Keycode::T => KeyCode::T,
        Keycode::U => KeyCode::U,
        Keycode::V => KeyCode::V,
        Keycode::W => KeyCode::W,
        Keycode::X => KeyCode::X,
        Keycode::Y => KeyCode::Y,
        Keycode::Z => KeyCode::Z,

        Keycode::Escape => KeyCode::Escape,

        Keycode::F1 => KeyCode::F1,
        Keycode::F2 => KeyCode::F2,
        Keycode::F3 => KeyCode::F3,
        Keycode::F4 => KeyCode::F4,
        Keycode::F5 => KeyCode::F5,
        Keycode::F6 => KeyCode::F6,
        Keycode::F7 => KeyCode::F7,
        Keycode::F8 => KeyCode::F8,
        Keycode::F9 => KeyCode::F9,
        Keycode::F10 => KeyCode::F10,
        Keycode::F11 => KeyCode::F11,
        Keycode::F12 => KeyCode::F12,
        Keycode::F13 => KeyCode::F13,
        Keycode::F14 => KeyCode::F14,
        Keycode::F15 => KeyCode::F15,
        Keycode::F16 => KeyCode::F16,
        Keycode::F17 => KeyCode::F17,
        Keycode::F18 => KeyCode::F18,
        Keycode::F19 => KeyCode::F19,
        Keycode::F20 => KeyCode::F20,
        Keycode::F21 => KeyCode::F21,
        Keycode::F22 => KeyCode::F22,
        Keycode::F23 => KeyCode::F23,

        Keycode::PrintScreen => KeyCode::Snapshot,
        Keycode::ScrollLock => KeyCode::Scroll,
        Keycode::Pause => KeyCode::Pause,
        Keycode::Insert => KeyCode::Insert,
        Keycode::Home => KeyCode::Home,
        Keycode::Delete => KeyCode::Delete,
        Keycode::End => KeyCode::End,
        Keycode::PageDown => KeyCode::PageDown,
        Keycode::PageUp => KeyCode::PageUp,
        Keycode::Left => KeyCode::Left,
        Keycode::Up => KeyCode::Up,
        Keycode::Right => KeyCode::Right,
        Keycode::Down => KeyCode::Down,
        Keycode::Return => KeyCode::Return,
        Keycode::Space => KeyCode::Space,
        Keycode::Caret => KeyCode::Caret,

        Keycode::NumLockClear => KeyCode::Numlock,
        Keycode::Num0 => KeyCode::Numpad0,
        Keycode::Num1 => KeyCode::Numpad1,
        Keycode::Num2 => KeyCode::Numpad2,
        Keycode::Num3 => KeyCode::Numpad3,
        Keycode::Num4 => KeyCode::Numpad4,
        Keycode::Num5 => KeyCode::Numpad5,
        Keycode::Num6 => KeyCode::Numpad6,
        Keycode::Num7 => KeyCode::Numpad7,
        Keycode::Num8 => KeyCode::Numpad8,
        Keycode::Num9 => KeyCode::Numpad9,

        Keycode::Quote => KeyCode::Apostrophe,
        Keycode::Asterisk => KeyCode::Asterisk,
        Keycode::KpPlus => KeyCode::Plus,
        Keycode::At => KeyCode::At,
        Keycode::Backslash => KeyCode::Backslash,
        Keycode::Calculator => KeyCode::Calculator,
        Keycode::CapsLock => KeyCode::Capital,
        Keycode::Colon => KeyCode::Colon,
        Keycode::Comma => KeyCode::Comma,
        Keycode::Equals => KeyCode::Equals,
        Keycode::LAlt => KeyCode::LAlt,
        Keycode::LeftBracket => KeyCode::LBracket,
        Keycode::LCtrl => KeyCode::LControl,
        Keycode::LShift => KeyCode::LShift,
        Keycode::LGui => KeyCode::LWin,
        Keycode::Mail => KeyCode::Mail,
        Keycode::MediaSelect => KeyCode::MediaSelect,
        Keycode::Minus => KeyCode::Minus,
        Keycode::Mute => KeyCode::Mute,
        Keycode::Computer => KeyCode::MyComputer,
        Keycode::Period => KeyCode::Period,
        Keycode::AudioPlay => KeyCode::PlayPause,
        Keycode::Power => KeyCode::Power,
        Keycode::AudioPrev => KeyCode::PrevTrack,
        Keycode::RAlt => KeyCode::RAlt,
        Keycode::RightBracket => KeyCode::RBracket,
        Keycode::RCtrl => KeyCode::RControl,
        Keycode::RShift => KeyCode::RShift,
        Keycode::RGui => KeyCode::RWin,
        Keycode::Semicolon => KeyCode::Semicolon,
        Keycode::Slash => KeyCode::Slash,
        Keycode::Sleep => KeyCode::Sleep,
        Keycode::Stop => KeyCode::Stop,
        Keycode::Sysreq => KeyCode::Sysrq,
        Keycode::Tab => KeyCode::Tab,
        Keycode::Underscore => KeyCode::Underline,
        Keycode::VolumeDown => KeyCode::VolumeDown,
        Keycode::VolumeUp => KeyCode::VolumeUp,

        Keycode::AcBookmarks => KeyCode::WebFavorites,
        Keycode::AcForward => KeyCode::WebForward,
        Keycode::AcHome => KeyCode::WebHome,
        Keycode::AcRefresh => KeyCode::WebRefresh,
        Keycode::AcSearch => KeyCode::WebSearch,
        Keycode::AcStop => KeyCode::WebStop,

        _ => return None,
    };

    Some(key_code)
}
