[package]
name = "elysium-framework"
version = "0.0.2"
edition = "2021"

[dependencies.elysium-ptr]
path = "../ptr"

[dependencies.libloading]
version = "0.7"

[dependencies.log]
default-features = false
version = "0.4"
