#pragma once

enum ClientFrameStage_t {
    FRAME_UNDEFINED = -1,
    FRAME_START,
    FRAME_NET_UPDATE_START,
    FRAME_NET_UPDATE_POSTDATAUPDATE_START,
    FRAME_NET_UPDATE_POSTDATAUPDATE_END,
    FRAME_NET_UPDATE_END,
    FRAME_RENDER_START,
    FRAME_RENDER_END,
    FRAME_NET_FULL_FRAME_UPDATE_ON_REMOVE
};

enum RenderViewInfo_t {
    RENDERVIEW_UNSPECIFIED = 0,
    RENDERVIEW_DRAWVIEWMODEL = (1 << 0),
    RENDERVIEW_DRAWHUD = (1 << 1),
    RENDERVIEW_SUPPRESSMONITORRENDERING = (1 << 2),
};

enum ClientDLLObserverMode_t {
    CLIENT_DLL_OBSERVER_NONE = 0,
    CLIENT_DLL_OBSERVER_DEATHCAM,
    CLIENT_DLL_OBSERVER_FREEZECAM,
    CLIENT_DLL_OBSERVER_FIXED,
    CLIENT_DLL_OBSERVER_IN_EYE,
    CLIENT_DLL_OBSERVER_CHASE,
    CLIENT_DLL_OBSERVER_ROAMING,
    CLIENT_DLL_OBSERVER_OTHER,
};
